version: '2'
services:
    web:
        image: shivergard/hyper-cli
        ports:
            - 80:8686
        volumes:
             - ./:/opt/hyper
             - ./storage:/root/.ssh
        command: '/opt/hyper/run.sh'